=== MarcusGitAccount/covid-ontology/Verbaliser/swatxml.dtd
<?xml version="1.0" encoding="utf-8"?>
<!ELEMENT swatontology (description*, lexicon*)>
<!ELEMENT description (title, text)>
<!ATTLIST description iri CDATA #REQUIRED>
<!ELEMENT title (#PCDATA)>
<!ATTLIST title type CDATA #REQUIRED>
<!ELEMENT text (subgroup)*>
<!ELEMENT subgroup (sentence)*>
<!ATTLIST subgroup id CDATA #REQUIRED>
<!ELEMENT sentence (#PCDATA | entity)*>
<!ATTLIST sentence axiom_id CDATA #IMPLIED>
<!ATTLIST sentence owlterm CDATA #IMPLIED>
<!ELEMENT entity (#PCDATA)>
<!ATTLIST entity iri CDATA #REQUIRED>
<!ELEMENT lexicon (singular, plural)>
<!ATTLIST lexicon type CDATA #REQUIRED>
<!ATTLIST lexicon identifier CDATA #REQUIRED>
<!ATTLIST lexicon pos CDATA #REQUIRED>
<!ELEMENT singular (#PCDATA)>
<!ELEMENT plural (#PCDATA)>

=== MarcusGitAccount/covid-ontology/Verbaliser/text/bookDefinitionsText.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="../SWATStylesheet.xsl"?>
<!DOCTYPE swatontology SYSTEM "../swatxml.dtd">
<swatontology>
<description iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">
<title type="individual">CHARLES DICKENS</title>
<text>
<subgroup id="Typology">
<sentence owlterm="classAssertion([class('http://www.w3.org/2002/07/owl#Thing'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#person'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man'),numberOfElements('5')],namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity> is all of the following: a <entity iri="http://www.w3.org/2002/07/owl#Thing">thing</entity>, a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#person">person</entity> and a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man">man</entity>, and so on (5 items).</sentence>
</subgroup>
<subgroup id="Description">
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#authorOf'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#authorOf">is author of</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">David Copperfield</entity>.</sentence>
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn">is resident in</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England">England</entity>.</sentence>
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#writtenBy'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">David Copperfield</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#writtenBy">is written by</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity>.</sentence>
</subgroup>
</text>
</description>
<description iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">
<title type="individual">DAVID COPPERFIELD</title>
<text>
<subgroup id="Typology">
<sentence owlterm="classAssertion([class('http://www.w3.org/2002/07/owl#Thing'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#novel'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#book')],namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">David Copperfield</entity> is all of the following: a <entity iri="http://www.w3.org/2002/07/owl#Thing">thing</entity>, a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#novel">novel</entity>, and a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#book">book</entity>.</sentence>
</subgroup>
<subgroup id="Description">
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#authorOf'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#authorOf">is author of</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">David Copperfield</entity>.</sentence>
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#writtenBy'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#DavidCopperfield">David Copperfield</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#writtenBy">is written by</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity>.</sentence>
</subgroup>
</text>
</description>
<description iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England">
<title type="individual">ENGLAND</title>
<text>
<subgroup id="Typology">
<sentence owlterm="classAssertion([class('http://www.w3.org/2002/07/owl#Thing'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#place'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#country')],namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England">England</entity> is all of the following: a <entity iri="http://www.w3.org/2002/07/owl#Thing">thing</entity>, a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#place">place</entity>, and a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#country">country</entity>.</sentence>
</subgroup>
<subgroup id="Description">
<sentence owlterm="objectPropertyAssertion(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn'),[namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#JaneAusten'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens')],namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England'))"><entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#JaneAusten">Jane Austen</entity> and <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#CharlesDickens">Charles Dickens</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn">are residents in</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England">England</entity>.</sentence>
</subgroup>
</text>
</description>
<description iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#Englishman">
<title type="class">ENGLISHMAN</title>
<text>
<subgroup id="Definition">
<sentence owlterm="equivalentClasses(class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#Englishman'),objectIntersectionOf(class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man'),objectHasValue(objectProperty('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn'),namedIndividual('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England'))))">An <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#Englishman">englishman</entity> is defined as a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man">man</entity> that <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#residentIn">is resident in</entity> <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#England">England</entity>.</sentence>
</subgroup>
<subgroup id="Typology">
<sentence owlterm="subClassOf(class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#Englishman'),[class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#person'),class('http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man')])">An <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#Englishman">englishman</entity> is both a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#person">person</entity>, and a <entity iri="http://www.semanticweb.org/ontologies/2010/4/Ontology1273848485010.owl#man">man</entity>.</sentence>
</subgroup>
<subgroup id="Examples">
